services:
  backend:
    image: node:22-alpine
    working_dir: /app/backend
    command: node src/app.js
    volumes:
      - ./backend:/app/backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"

  frontend:
    image: node:22-alpine
    working_dir: /app/frontend
    command: npm run dev -- --host
    volumes:
      - ./frontend:/app/frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:3000"
    depends_on:
      - backend
